sim: 'TNG50-4'

TNGCluster_flag: False
mp_flag: True
zooniverse_flag: False
centrals_flag: False
    
max_snap: 99
min_snap: 0

tlim: 31622.776601683792 # = 10.**(4.5) K; cutoff between cold and hot gas
jellyscore_min: 16
treeName: 'SubLink_gal'

SubfindIndices: False
SubfindGasRadProf: False
SubfindSnapshot: False
TracerTracks: False


