sim: 'TNG50-4' # options are 'TNG*-*;, for 50, 100, 300 and -1, -2, -3 -4 or L680n8192TNG

TNGCluster_flag: False
mp_flag: False
zooniverse_flag: False
centrals_flag: False
tracers_flag: False
allsubhalos_flag: False
Nmpcores: 8
    
max_snap: 99
min_snap: 0

first_snap: 0
last_snap: 99

tlim: 31622.776601683792 # = 10.**(4.5) K; cutoff between cold and hot gas
jellyscore_min: 16
treeName: 'SubLink_gal'
zooniverse_key: 'inspected'
ins_key: 'inspected'
jel_key: 'jellyfish'
non_key: 'nonjellyf'

SubfindIndices: False
SubfindGasRadProf: False
run_SGRP: False
run_SGRP_PP: False
SubfindSnapshot: False
run_SS: False
run_SS_PP: False
TracerTracks: False
track_tracers: False
find_tracers: False

zooniverse_snapfirst: 67 # require a zooniverse inspection (or jellyfish classification) at or after this snap
Nsnaps_PP: 5 # number of consecutive snaps to be considered pre-processed
M200c0_lolim_PP: 1.e+11 # minimum halo mass of a pre-processing host

