sim: 'TNG50-4'

TNGCluster_flag: False
mp_flag: True
zooniverse_flag: False
centrals_flag: False
tracers_flag: True
    
max_snap: 99
min_snap: 0

first_snap: 99
last_snap: 99

tlim: 31622.776601683792 # = 10.**(4.5) K; cutoff between cold and hot gas
jellyscore_min: 16
treeName: 'SubLink_gal'
zooniverse_key: 'inspected'
ins_key: 'inspected'
jel_key: 'jellyfish'
non_key: 'nonjellyf'

SubfindIndices: False
SubfindGasRadProf: True
run_SGRP: False
run_SCGP_PP: True
SubfindSnapshot: False
TracerTracks: False


